config:
  backup: true
  banner: true
  create: true
  dotpath: ../dotfiles/git
  keepdot: true
  link_dotfile_default: link
  link_on_import: link
dotfiles:
  gitconfig.local:
    dst: ~/.gitconfig.local
    src: gitconfig.local.symlink
  gitconfig:
    dst: ~/.gitconfig
    src: gitconfig.symlink
  gitignore:
    dst: ~/.gitignore
    src: gitignore.symlink
profiles:
