config:
  backup: true
  banner: true
  create: true
  dotpath: ../dotfiles/gpg
  keepdot: true
  link_dotfile_default: link
  link_on_import: link
dotfiles:
  config:
    dst: ~/gpg.conf
    src: gpg.conf.symlink
profiles:
