config:
  backup: true
  banner: true
  create: true
  dotpath: ../dotfiles/ssh
  keepdot: true
  link_dotfile_default: link
  link_on_import: link
dotfiles:
  config:
    dst: ~/.ssh/config
    src: config.symlink
profiles:
