config:
  backup: true
  banner: true
  create: true
  dotpath: ../dotfiles/system
  keepdot: true
  link_dotfile_default: link
  link_on_import: link
dotfiles:
  dircolors:
    dst: ~/.dircolors
    src: dircolors.symlink
profiles:
