config:
  backup: true
  banner: true
  create: true
  dotpath: ../dotfiles/tmux
  keepdot: true
  link_dotfile_default: link
  link_on_import: link
dotfiles:
  tmux-conf:
    dst: ~/.tmux.conf
    src: .tmux/.tmux.conf
  tmux-conf-local:
    dst: ~/.tmux.conf.local
    src: tmux.conf.local.symlink
profiles:
