config:
  backup: true
  banner: true
  create: true
  dotpath: ../dotfiles/zsh
  keepdot: true
  link_dotfile_default: link
  link_on_import: link
dotfiles:
  zshenv:
    dst: ~/.zshenv
    src: zshenv.symlink
  zshrc:
    dst: ~/.zshrc
    src: zshrc.symlink
  pk10:
    dst: ~/.p10k.zsh
    src: p10k.zsh.symlink
profiles:
